### ISSUE TITLE
Wait at 0% while training.Epoch 0:       0%              0/13000

### ISSUE THREAD

**Issue by cats0212** [rasmushaugaard/surfemb#4]
Hi, i run 'python -m surfemb.scripts.train ycbv', and ./data/bop/ycbv/models have 21 .ply files, and 80 folder in ./data/bop/ycbv/train_real. I did not use synth imgs, but the program always 0%. Is the program preprocessing image information,crop object from img?I waited a dozen hours and it was still 0%. like Epoch 0:   0%.  The python is still running.Do I have to wait a long time before  train model?Are you in a similar situation?

But if I just have 3 .ply files in ./data/bop/ycba/models,and 1 folder in ./data/bop/ycbv/train_real,it will soon(3 - 4 minutes) train cnn .Finally, the trained model is obtained.
For example, obj_000008.ply, obj_000014.ply, obj_000021.ply in ./data/bop/ycba/models, 000000 in ./data/bop/ycbv/train_real(imgs in 000000 only have 3 types of objects, obj_8, obj_14, obj_21).

If I want to train all the objects in ycbv at once, Do I have to wait longer?I'm using a server, CPU performance is not weak.

{
    "os": "Linux-4.15.0-175-generic-x86_64-with-debian-buster-sid",
    "python": "3.7.11",
    "heartbeatAt": "2022-04-09T09:34:05.311715",
    "startedAt": "2022-04-09T09:34:02.496814",
    "docker": null,
    "gpu": "GeForce RTX 3090",
    "gpu_count": 8,
    "cpu_count": 40,
    "cuda": null,
    "args": [],
    "state": "running",
    "program": "-m surfemb.scripts.train",
    "git": {
        "remote": "https://github.com/rasmushaugaard/surfemb.git",
        "commit": "46f46ddc5670848d696968dc8ec65c8ce62b16a8"
    },
    "email": "qwzf@qq.com",
    "root": "/home/aa/prjs/surfemb",
    "host": "sddx-PR4908P",
    "username": "aa",
    "executable": "/home/aa/anaconda3/envs/d2_1.10/bin/python"
}

logs:
2022-04-09 11:02:46,213 INFO    MainThread:16337 [wandb_setup.py:_flush():75] Loading settings from /home/aa/.config/wandb/settings
2022-04-09 11:02:46,214 INFO    MainThread:16337 [wandb_setup.py:_flush():75] Loading settings from /home/aa/prjs/bcnet/pose/surfemb/wandb/settings
2022-04-09 11:02:46,214 INFO    MainThread:16337 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'api_key': '***REDACTED***', 'mode': 'offline', '_require_service': 'True'}
2022-04-09 11:02:46,214 WARNING MainThread:16337 [wandb_setup.py:_flush():75] Could not find program at -m surfemb.scripts.train
2022-04-09 11:02:46,214 INFO    MainThread:16337 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m surfemb.scripts.train'}
2022-04-09 11:02:46,214 INFO    MainThread:16337 [wandb_init.py:_log_setup():405] Logging user logs to /home/aa/prjs/bcnet/pose/surfemb/wandb/offline-run-20220409_110246-3fewafz3/logs/debug.log
2022-04-09 11:02:46,214 INFO    MainThread:16337 [wandb_init.py:_log_setup():406] Logging internal logs to /home/aa/prjs/bcnet/pose/surfemb/wandb/offline-run-20220409_110246-3fewafz3/logs/debug-internal.log
2022-04-09 11:02:46,215 INFO    MainThread:16337 [wandb_init.py:init():439] calling init triggers
2022-04-09 11:02:46,215 INFO    MainThread:16337 [wandb_init.py:init():443] wandb.init called with sweep_config: {}
config: {}
2022-04-09 11:02:46,215 INFO    MainThread:16337 [wandb_init.py:init():492] starting backend
2022-04-09 11:02:46,228 INFO    MainThread:16337 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-09 11:02:46,232 INFO    MainThread:16337 [wandb_init.py:init():501] backend started and connected
2022-04-09 11:02:46,238 INFO    MainThread:16337 [wandb_init.py:init():565] updated telemetry
2022-04-09 11:02:46,578 INFO    MainThread:16337 [wandb_init.py:init():625] starting run threads in backend
2022-04-09 11:02:49,104 INFO    MainThread:16337 [wandb_run.py:_console_start():1733] atexit reg
2022-04-09 11:02:49,106 INFO    MainThread:16337 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-04-09 11:02:49,107 INFO    MainThread:16337 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-04-09 11:02:49,108 INFO    MainThread:16337 [wandb_run.py:_redirect():1667] Redirects installed.
2022-04-09 11:02:49,109 INFO    MainThread:16337 [wandb_init.py:init():664] run started, returning control to user process
2022-04-09 11:02:49,130 INFO    MainThread:16337 [wandb_run.py:_config_callback():992] config_cb None None {'n_objs': 21, 'emb_dim': 12, 'n_pos': 1024, 'n_neg': 1024, 'lr_cnn': 0.0003, 'lr_mlp': 3e-05, 'mlp_name': 'siren', 'mlp_hidden_features': 256, 'mlp_hidden_layers': 2, 'key_noise': 0.001, 'warmup_steps': 2000, 'separate_decoders': True, 'pa_sigma': 0.0, 'align_corners': False, 'dataset': 'ycbv', 'n_valid': 200, 'res_data': 256, 'res_crop': 224, 'batch_size': 16, 'num_workers': 'None', 'min_visib_fract': 0.1, 'max_steps': 500000, 'gpus': 2, 'debug': False, 'ckpt': 'None', 'synth': False, 'real': True}
2022-04-09 11:07:50,141 WARNING MsgRouterThr:16337 [router.py:message_loop():76] message_loop has been closed

**Comment by cp1108** [comment]
And,I used [ycbv-jwpvdij1.compact.ckpt](https://github.com/rasmushaugaard/surfemb/releases/download/v0.0.1/ycbv-jwpvdij1.compact.ckpt) to infer test datasets in ycbv(python -m surfemb.scripts.infer), then python -m surfemb.scripts.misc.format_results_for_eval, the score in results all is negative, for example，-0.339 , -0.401.Is that normal？
![image](https://user-images.githubusercontent.com/56954781/162874481-5241d3d0-e7a2-4f35-bb11-a053d4bc0d4f.png)

**Comment by cp1108** [comment]
Through your trained model,I get the file ycbv-jwpvdij1-refine-pose-score_ycbv-test.csv.
Then python ./bop_toolkit/bop_toolkit_lib/eval_bop19.py  get a result
`{
  "bop19_average_recall": 0.5618441264451451,
  "bop19_average_recall_mspd": 0.7611933058452582,
  "bop19_average_recall_mssd": 0.4954887218045113,
  "bop19_average_recall_vsd": 0.42885035168566576,
  "bop19_average_time_per_image": 4.59347986459732
}`
But  average_recall(ycbv)  is 0.653 in your paper.

**Comment by rasmushaugaard** [comment]
I've only trained models with all the objects. Loading objects and crop info should not take more than a minute.
Have you tried with the conda environment?

**Comment by cp1108** [comment]
I tried with the conda environment,but cuda 11.1，because gpu 3090 is not compatible cuda 10.2.
pytorch                   1.11.0
pytorch-lightning         1.6.0 
torchvision               0.12.0
if I run python -m surfemb.scripts.train ycbv with real imgs, It's still the same problem.
if I run python -m surfemb.scripts.train tless,and get : 

Traceback (most recent call last):aded (0.000 MB deduped)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/aa/prjs/bcnet/pose/surfemb/surfemb/scripts/train.py", line 127, in <module>
    main()
  File "/home/aa/prjs/bcnet/pose/surfemb/surfemb/scripts/train.py", line 123, in main
    trainer.fit(model, loader_train)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 771, in fit
    self._call_and_handle_interrupt(
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 722, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/spawn.py", line 78, in launch
    mp.spawn(
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/spawn.py", line 101, in _wrapping_function
    results = function(*args, **kwargs)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 812, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1237, in _run
    results = self._run_stage()
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1324, in _run_stage
    return self._run_train()
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1354, in _run_train
    self.fit_loop.run()
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 269, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 171, in advance
    batch = next(data_fetcher)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 259, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 273, in _fetch_next_batch
    batch = next(iterator)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 553, in __next__
    return self.request_next_batch(self.loader_iters)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 565, in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 99, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 157, in default_collate
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 157, in <dictcomp>
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 180, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'trimesh.caching.TrackedArray'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 160, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 160, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/aa/anaconda3/envs/surfemb/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 180, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'trimesh.caching.TrackedArray'>



wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb:                                                                                
wandb: Synced stoic-plant-14: https://wandb.ai/chenpu/surfemb/runs/3lgv45b1
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: data/logs/wandb/run-20220414_113212-3lgv45b1/logs
![image](https://user-images.githubusercontent.com/56954781/163309674-8ad508b0-b777-486b-9247-373e9a11a4ec.png)

![捕获](https://user-images.githubusercontent.com/56954781/163309716-f4c34c83-d466-4ccb-9876-d25477c6b95e.PNG)

**Comment by cats0212** [comment]
I have tried with the conda environment.If I use only one gpu,it is all right,but when I use 2 or 4 gpus,it is can not successful train.I don't know what the reason is.Did you use 2 or more gpus for training?thank you

**Comment by cats0212** [comment]
But if I only train a few objects , I can use 2 or 4 gpus to train.  This bug is very confusing.
