### ISSUE TITLE
remove invisible parts of the objects

### ISSUE THREAD

**Issue by woodcore-an** [rasmushaugaard/surfemb#8]
when i try to run `python -m surfemb.scripts.misc.surface_samples_remesh_visible tless`,

it cause:
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/robot/miniconda3/envs/surfemb/lib/python3.8/site-packages/cv2.cpython-38-x86_64-linux-gnu.so)

i install opencv-python==4.1.2.30 to fix it.

But it cause another problem:
Traceback (most recent call last):
  File "/home/zzz/miniconda3/envs/surfemb-test/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zzz/miniconda3/envs/surfemb-test/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zzz/github/surfemb/surfemb/scripts/misc/surface_samples_remesh_visible.py", line 29, in <module>
    ms.repair_non_manifold_edges_by_removing_faces()
AttributeError: 'pymeshlab.pmeshlab.MeshSet' object has no attribute 'repair_non_manifold_edges_by_removing_faces'

**Comment by cats0212** [comment]
Hi,I have the same error.How did you solve this problem?Thank you.
Traceback (most recent call last):
  File "/home/aa/anaconda3/envs/surfemb3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/aa/anaconda3/envs/surfemb3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/aa/prjs/data/surfemb/surfemb/scripts/misc/surface_samples_remesh_visible.py", line 29, in <module>
    ms.repair_non_manifold_edges_by_removing_faces()
AttributeError: 'pymeshlab.pmeshlab.MeshSet' object has no attribute 'repair_non_manifold_edges_by_removing_faces'

**Comment by cats0212** [comment]
I install pymeshlab==0.2.1 to fix it,but it cause another problem.
#11
